name: release
on: 
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v1

      - name: create venv & activate
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: install packagaes
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: build
        run: python3 setup.py py2app  

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/Rush-Hour
          asset_name: Rush-Hour
          tag: ${{ github.ref }}
          overwrite: true
          body: "Testing automatic release"
