name: release
on: 
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v1

      - name: create venv & activate
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: install packagaes
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: build
        run: python3 setup.py py2app  

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
